### ISSUE TITLE
Rollup 3.x support is not published to NPM

### ISSUE THREAD

**Issue by RoryDuncan** [NotWoods/rollup-plugin-consts#15]
Hey @NotWoods —Thanks for maintaining. Minor hiccup for rollup 3.x support.

The latest version on [npm is `v1.1.0`](https://www.npmjs.com/package/rollup-plugin-consts), **not**  the `v1.1.1` patch.

Publishing is [the final part of @ROpdebee's PR](https://github.com/NotWoods/rollup-plugin-consts/pull/13#issuecomment-1288049210) to have rollup 3.x support for everyone.

### Temporary workaround

For others looking for an interim fix—install latest via github:
```sh
npm install https://github.com/NotWoods/rollup-plugin-consts
```

**Comment by randomfog42** [comment]
Hey @NotWoods 
I'm waitting for this too :)

**Comment by NotWoods** [comment]
A new version is now published!
